services:
  poop-bot:
    image: 'spring-boot'
    build:
      context: .
    container_name: spring-boot
    depends_on:
      - postgres
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/PoopDB
      - SPRING_DATASOURCE_USERNAME=${DB_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${DB_PASSWORD}
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update

  postgres:
    image: postgres
    container_name: postgres
    restart: always
    ports:
      - '5432:5432'
      #volumes:
      #- ./pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=PoopDB
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}